# Generated by Django 2.2.19 on 2022-08-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ингридиента')),
                ('quantity', models.CharField(max_length=100, verbose_name='Количество')),
                ('unit', models.CharField(max_length=100, verbose_name='Единица измерения')),
            ],
        ),
    ]
