# Generated by Django 2.2.19 on 2022-08-19 11:38

import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220819_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.validators.validate_tag_color], verbose_name='Цветовой HEX-код'),
        ),
    ]
